version: "3.9"
services:
  backend:
    build:
      context: ./icashx-backend
    container_name: icashx-backend
    ports:
      - "8000:8000"
    env_file:
      - ./icashx-backend/.env
    networks:
      - icashx-net

  frontend:
    build:
      context: ./icashx-frontend
    container_name: icashx-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - icashx-net

networks:
  icashx-net:
    driver: bridge